### ISSUE TITLE
Mario Kart 7 bcsar

### ISSUE THREAD

**Issue by milesthecreator** [kr3nshaw/caesar#8]
The program couldn't extract the content of the bcsar.
![Untitled](https://user-images.githubusercontent.com/45196539/101549077-78ec6c00-39c6-11eb-80b2-f42d87cf87a6.png)

**Comment by MDHEXT** [comment]
@milesthecreator Hi miles, you're from khinsider, correct? This issue is with MK7s bcsar encoding scheme. it seems to use an older version of the 3DS nintendoware SDK that caesar cannot currently read. A solution for this issue has been being worked on since last year, however, we cannot find the exact cause of the issue.

**Comment by milesthecreator** [comment]
I see.. That's too bad, hope a solution comes up someday.
Also, yes, it's me from khinsider!

**Comment by kr3nshaw** [comment]
Fixed in 0.3.4.
